name: Final

on:
  push:
    tags: "**"

jobs:
  # test:
  #   name: Running test workflow on ubuntu-latest
  #   uses: ./.github/workflows/test-template.yaml
  #   with:
  #     runs-on: ubuntu-latest

  docker:
    name: Build and push Docker image ${{ github.event_name }} on ${{ github.ref }}
    # Only start this job after job `test` finished successfully
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checking out ${{ github.ref }} ${{ github.sha }}
        uses: actions/checkout@v3
      - name: Setup QEMU for Buildx
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_GITHUB_ACTION }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/github-action-khonhai:latest
